<?php

namespace BoncoinBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Delete all annonces from database
     */
    public function deleteAll()
    {
        $connection = $this->getEntityManager()->getConnection();
        $dbPlatform = $connection->getDatabasePlatform();

        $connection->executeUpdate($dbPlatform->getTruncateTableSQL('annonce'));
    }
}
